// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-J7y3ckBmBateu6DxNnnyqh8bWTakiI',
    appId: '1:11289896151:web:2bfd1f8e7ef7e0588d7c92',
    messagingSenderId: '11289896151',
    projectId: 'phoenix-8549c',
    authDomain: 'phoenix-8549c.firebaseapp.com',
    storageBucket: 'phoenix-8549c.appspot.com',
    measurementId: 'G-WTKT0WW0QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eqZpVkyeSLzrcDJOHUa-MTCtwcnzCRs',
    appId: '1:11289896151:android:15f29d959c7227848d7c92',
    messagingSenderId: '11289896151',
    projectId: 'phoenix-8549c',
    storageBucket: 'phoenix-8549c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCACKPLzFbCK5fdDRUlBcNb0vTfKgQGLV4',
    appId: '1:11289896151:ios:8cfd031aed27f44b8d7c92',
    messagingSenderId: '11289896151',
    projectId: 'phoenix-8549c',
    storageBucket: 'phoenix-8549c.appspot.com',
    iosBundleId: 'com.example.audioReacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCACKPLzFbCK5fdDRUlBcNb0vTfKgQGLV4',
    appId: '1:11289896151:ios:8cfd031aed27f44b8d7c92',
    messagingSenderId: '11289896151',
    projectId: 'phoenix-8549c',
    storageBucket: 'phoenix-8549c.appspot.com',
    iosBundleId: 'com.example.audioReacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-J7y3ckBmBateu6DxNnnyqh8bWTakiI',
    appId: '1:11289896151:web:1b9bb0e5c114b6a18d7c92',
    messagingSenderId: '11289896151',
    projectId: 'phoenix-8549c',
    authDomain: 'phoenix-8549c.firebaseapp.com',
    storageBucket: 'phoenix-8549c.appspot.com',
    measurementId: 'G-84NXY1NBLG',
  );
}
